apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog
  namespace: service-a
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: blog
            port:
              number: 8080
        path: /
        pathType: Prefix
